apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.outerService.name }}-service-lb
  labels:
    app: "{{ .Values.outerService.name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.outerService.name }}"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

