apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.outerService.clusterIP}}
  labels:
    app: "{{ .Values.outerService.name }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.outerService.name }}"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
