apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-exposed
  labels:
    app: "{{ .Values.name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

